fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0 # Use the ref you want to point at
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
  - id: yamllint
    args: [-c=.yamllint]

- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: v1.3.0
  hooks:
  - id: nixpkgs-fmt

# TODO: Enable once nix is actually installed
# - repo: https://github.com/astro/deadnix
#   rev: efcd46e3827d1e42e8f2f9cb045dfb34caeb43f5
#   hooks:
#   - id: deadnix
#     #args: [--edit] # Uncomment to automatically modify files
#     stages: [commit]
