version: "3"

vars:
  PREFIX: env PATH="${HOME}/nix-config/.task:/nix/var/nix/profiles/default/bin"

includes:
  precommit: .taskfiles/PrecommitTasks.yml
  nix: .taskfiles/NixTasks.yml

tasks:
  default:
    silent: true
    cmds:
    - task -l
